### PR TITLE
added the content of index file

### PR DESCRIPTION
**Pull request by RashJrEdmund**

### CODE REVIEW

**Comment by nganifaith** [comment]
@RashJrEdmund take a second look and submit another request

**Review by nganifaith — CHANGES_REQUESTED** [review]
Great job so far @RashJrEdmund just a little changes a we will be there.

- [ ] readmore button missing some details
- [ ] comment count missing details

**Comment by nganifaith** [comment]
@RashJrEdmund Ahead and merge

**Comment by RashJrEdmund** [comment]
alas

**Pull request merged**
